gitRepo:
  gitProvider: git_test_go
  path: complexmathguy/spring-demo
  TestDBUrl: 
  TestDBName: spring-demo_test_db
  TestDBPassword: 
  TestDBDialect: org.hibernate.dialect.MySQL8Dialect 
  TestDBDriver: com.mysql.cj.jdbc.Driver
  DockerUserName: tylertravismya
  DockerPassword: 69cutlass
  DockerOrgName: theharbormaster
  DockerRepo: spring-demo
  DockerHost: 
  DockerTag: latest
